name: TheChicksDish.com
favicon: null
layout_spectrum: 0.9994704613927752
typography_spectrum: 0.6131151632871479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7096285307779908
  lightness: 0.7118367208167911
  saturation: 0.3550821184180677
  rhythmicContrast: 0.14438446331769228
purpose: []
